spring.application.name=ipl-stats-be


application.boot.message=Message from Dev Env
spring.liquibase.change-log=classpath:db/changelog/main-liquibase.xml


spring.datasource.url=jdbc:postgresql://dpg-cur8acpu0jms73cd4u1g-a.oregon-postgres.render.com/feb_db?currentSchema=dev
spring.datasource.username=feb_db_user
spring.datasource.password=ruadzdiIc9awEwBIHxZUrKNCpDVy4NN4
spring.datasource.port=5432


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true